apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: totalbody-static
  namespace: homeserver
spec:
  storageClassName: nfs-home
  resources:
    requests:
      storage: 100Mi
  accessModes:
    - ReadWriteMany
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-conf
  namespace: homeserver
spec:
  storageClassName: nfs-home
  resources:
    requests:
      storage: 10Mi
  accessModes:
    - ReadWriteMany