---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ddclient-pvc
  namespace: ddclient
spec:
  storageClassName: fileserver-nfs
  resources:
    requests:
      storage: 5Mi
  accessModes:
    - ReadWriteMany