apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: szuszinho@yahoo.hu
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef: 
      name: issuer-account-key
    solvers:
    - dns01:
        cloudflare:
          email: szuszinho@yahoo.hu
          apiKeySecretRef:
            name: cloudflare-api-key-secret
            key: api-key
      selector:
        dnsZones:
        - "szuszi.eu"
        - "totalbody.hu"