---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-claim
  namespace: homeserver
spec:
  storageClassName: nfs-home
  resources:
    requests:
      storage: 50Mi
  accessModes:
    - ReadWriteMany