apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
   - 10.10.10.200-10.10.10.209
#   - 172.16.16.200-172.16.16.240
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: config
  namespace: metallb-system
spec:
  ipAddressPools:
  - first-pool
